name: Check new version

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *' # every month first day

permissions:
  contents: write
  pull-requests: write

jobs:
  check_version:
    uses: mpvkit/BuildShared/.github/workflows/check_version.yml@main
    secrets: inherit
    with:
      repository: 'openssl/openssl'
      library: 'openssl'
      pr_body: |
        {REPOSITORY_URL}/blob/{NEW_VERSION}/CHANGES.md

        {REPOSITORY_URL}/compare/{OLD_VERSION}...{NEW_VERSION}
